### ISSUE TITLE
Height-by-rows bug with drag and drop

### ISSUE THREAD

**Issue by mattheol** [vaadin/vaadin#72] opened 2020-08-16 19:37 UTC
Issue with grid when height-by-rows is enabled.
Scroll is blinking and cannot drop dragged item below last item.
Workaround is to add footer, but it's impossible to change height of it.
![image](https://user-images.githubusercontent.com/38963051/90342317-8a6ccb00-e007-11ea-8ae3-aa046111a721.png)

**Comment by tomivirkki** [comment] 2020-08-17 07:42
Closing as a duplicate of https://github.com/vaadin/vaadin-grid-flow/issues/830

**Closed as completed by tomivirkki** 2020-08-17 07:42 UTC
